### ISSUE TITLE
`require': cannot load such file -- webrick (LoadError) 오류 해결

### ISSUE THREAD

**Issue by ChoSeyoung** [ChoSeyoung/neo-leul-jekyll-te-nikka#1]
에러 전문
```
Configuration file: /Users/csy/WebstormProjects/neo-leul-jekyll-te-nikka/_config.yml
            Source: /Users/csy/WebstormProjects/neo-leul-jekyll-te-nikka
       Destination: /Users/csy/WebstormProjects/neo-leul-jekyll-te-nikka/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Jekyll Feed: Generating feed for posts
                    done in 0.576 seconds.
 Auto-regeneration: enabled for '/Users/csy/WebstormProjects/neo-leul-jekyll-te-nikka'
                    ------------------------------------------------
      Jekyll 4.2.2   Please append `--trace` to the `serve` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
/Users/csy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/jekyll-4.2.2/lib/jekyll/commands/serve/servlet.rb:3:in `require': cannot load such file -- webrick (LoadError)
        from /Users/csy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/jekyll-4.2.2/lib/jekyll/commands/serve/servlet.rb:3:in `<top (required)>'
        from /Users/csy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:179:in `require_relative'
        from /Users/csy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:179:in `setup'
        from /Users/csy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:100:in `process'
        from /Users/csy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from /Users/csy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `each'
        from /Users/csy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from /Users/csy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        from /Users/csy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from /Users/csy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from /Users/csy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from /Users/csy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from /Users/csy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from /Users/csy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/jekyll-4.2.2/exe/jekyll:15:in `<top (required)>'
        from /Users/csy/.rbenv/versions/3.1.1/bin/jekyll:25:in `load'
        from /Users/csy/.rbenv/versions/3.1.1/bin/jekyll:25:in `<top (required)>'
        from /Users/csy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/cli/exec.rb:58:in `load'
        from /Users/csy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /Users/csy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/cli/exec.rb:23:in `run'
        from /Users/csy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/cli.rb:483:in `exec'
        from /Users/csy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /Users/csy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/csy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /Users/csy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/cli.rb:31:in `dispatch'
        from /Users/csy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /Users/csy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/cli.rb:25:in `start'
        from /Users/csy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/exe/bundle:48:in `block in <top (required)>'
        from /Users/csy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
        from /Users/csy/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/exe/bundle:36:in `<top (required)>'
        from /Users/csy/.rbenv/versions/3.1.1/bin/bundle:25:in `load'
        from /Users/csy/.rbenv/versions/3.1.1/bin/bundle:25:in `<main>'
```

**Comment by ChoSeyoung** [comment]
`bundle add webrick` 으로 `webrick`을 추가
